## Experiment 2
### Perform different array slicing methods


In [2]:
import numpy as np

# Define a 2D numpy array with updated values
matrix = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# Slice the array to get the first two rows and the first two columns
print("\nSlicing the first two rows and columns:")
print(matrix[:2, :2])

# Slice the array to get the last row
print("\nSlicing the last row:")
print(matrix[-1, :])

# Slice the array to get the second column
print("\nSlicing the second column:")
print(matrix[:, 1])

# Slice with a step
print("\nSlicing with a step:")
print(matrix[::2, ::2])


Slicing the first two rows and columns:
[[10 20]
 [40 50]]

Slicing the last row:
[70 80 90]

Slicing the second column:
[20 50 80]

Slicing with a step:
[[10 30]
 [70 90]]
